version: '3.9'
services:
  db:
    image: mysql:8.0.34
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: docker
      MYSQL_PASSWORD: root123
      MYSQL_DATABASE: erudio
      MYSQL_TCP_PORT: 3308
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - rest-network
  erudio:
    image: tadeuwohlers/erudio
    container_name: erudio
    restart: always
    build: ./
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: docker
      SPRING.DATASOURCE.PASSWORD: root123
    ports:
      - 80:80
    expose:
      - 80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - rest-network
networks:
  rest-network:
    driver: bridge